from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.audit import AuditStore
from src.pipeline import DailyPipeline
from src.schemas import Asset, AssetMetrics, PortfolioSnapshot, Position


def build_demo_snapshot() -> PortfolioSnapshot:
    positions = [
        Position(
            asset=Asset(symbol="AAPL", name="Apple Inc.", sector="Technology"),
            quantity=10,
            average_cost=175.0,
            market_price=210.0,
            market_value=2100.0,
            weight=0.42,
            unrealized_pnl=350.0,
            unrealized_pnl_pct=0.20,
        ),
        Position(
            asset=Asset(symbol="MSFT", name="Microsoft Corp.", sector="Technology"),
            quantity=6,
            average_cost=380.0,
            market_price=420.0,
            market_value=2520.0,
            weight=0.50,
            unrealized_pnl=240.0,
            unrealized_pnl_pct=0.105,
        ),
    ]
    return PortfolioSnapshot(
        snapshot_id="demo_snapshot_001",
        as_of=datetime.utcnow(),
        positions=positions,
        cash=380.0,
        total_market_value=5000.0,
        total_cost=4410.0,
    )


def build_demo_metrics() -> list[AssetMetrics]:
    now = datetime.utcnow()
    return [
        AssetMetrics(
            symbol="AAPL",
            as_of=now,
            daily_return=-0.012,
            volatility_20d=0.045,
            max_drawdown_60d=-0.09,
            moving_average_20d=205.0,
            moving_average_60d=198.0,
            metadata={"latest_price": 210.0},
        ),
        AssetMetrics(
            symbol="MSFT",
            as_of=now,
            daily_return=0.004,
            volatility_20d=0.028,
            max_drawdown_60d=-0.06,
            moving_average_20d=410.0,
            moving_average_60d=395.0,
            metadata={"latest_price": 420.0},
        ),
        AssetMetrics(
            symbol="NVDA",
            as_of=now,
            daily_return=0.018,
            volatility_20d=0.039,
            max_drawdown_60d=-0.12,
            moving_average_20d=1120.0,
            moving_average_60d=1080.0,
            metadata={"latest_price": 1160.0},
        ),
    ]


def main() -> None:
    pipeline = DailyPipeline()
    brief = pipeline.run(
        snapshot=build_demo_snapshot(),
        asset_metrics=build_demo_metrics(),
        news_summary="Demo news summary: technology sector sentiment is mixed, with valuation risk still elevated.",
    )

    llm_input = brief.model_dump(mode="json")
    audit = AuditStore().save_daily_run(
        brief=brief,
        llm_input=llm_input,
        llm_output="Demo report output placeholder. In production this is generated by the LLM from DailyBrief only.",
    )

    print(f"DailyBrief: {brief.brief_id}")
    print(f"Signals: {len(brief.signals)}")
    print(f"Risk themes: {len(brief.risk_themes)}")
    print(f"Audit run: {audit.audit_id}")


if __name__ == "__main__":
    main()
